---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.82, CPAN::Meta::Converter version 2.133380'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-Summary
no_index:
  directory:
    - t
    - inc
requires:
  Exporter: 0
  HTML::TreeBuilder: 0
  constant: 0
  perl: 5.006
  strict: 0
  vars: 0
  warnings: 0
version: 0.018
